# Generated by Django 3.1.4 on 2021-01-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='breakfast_tag',
            field=models.BooleanField(default=False, verbose_name='завтрак'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dinner_tag',
            field=models.BooleanField(default=False, verbose_name='обед'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='supper_tag',
            field=models.BooleanField(default=False, verbose_name='ужин'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
