# Generated by Django 3.1.4 on 2021-01-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210115_0227'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('title', 'unit'), name='unique_ingredient'),
        ),
    ]
